### PR TITLE
docs: clone with --recurse-submodules

### PR DESCRIPTION
**Pull request by dllud**

### CODE REVIEW

**Comment by m-simonelli** [comment]
Perhaps we should add a note along the lines of "if you've already cloned, do `git submodule --init --update`"

**Comment by dllud** [comment]
Done.

**Review by m-simonelli — APPROVED** [review]
LGTM

**Comment by pospeselr** [comment]
cherry-picked into main as 6827d50eb7dc79047b50764a30fac5d7758cc3b9

**Pull request closed without merging**
